# Generated by Django 3.1.7 on 2021-03-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_scheduleentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['day', 'start_time'], 'verbose_name_plural': 'Schedule entries'},
        ),
    ]
