name: MakeMyDay CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: |
          python -m pylint --load-plugins=pylint_django --disable=django-not-configured ./src
        env:
          PYTHONPATH: ./src
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          python src/manage.py test
